-- Create EMPLOYEE table with constraints
CREATE TABLE IF NOT EXISTS EMPLOYEE (
    EMP_ID INTEGER PRIMARY KEY,
    NAME TEXT NOT NULL,
    DEPARTMENT TEXT NOT NULL,
    SALARY INTEGER CHECK (SALARY > 0),
    EXPERIENCE INTEGER
);

-- Insert sample records
INSERT INTO EMPLOYEE (EMP_ID, NAME, DEPARTMENT, SALARY, EXPERIENCE) VALUES
(101, 'ALICE', 'IT', 60000, 3),
(102, 'BOB', 'HR', 45000, 2),
(103, 'CHARLIE', 'IT', 80000, 6),
(104, 'DAVID', 'FINANCE', 70000, 5),
(105, 'EVA', 'HR', 50000, 4);

-- 1. Find average salary per departmen
